/* Run: npm install; npx playwright install chromium; npm test (server starts automatically). */
const { chromium, webkit }=require('playwright');
const { spawn }=require('node:child_process');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
(async()=>{
 const server=spawn('python3',['-m','http.server','8766','--directory',root],{stdio:'ignore'});
 let browser;const results=[];
 try{for(let i=0;i<50;i++){try{await fetch('http://localhost:8766');break}catch{await new Promise(r=>setTimeout(r,100))}}
 browser=await (process.env.STOCK_BROWSER==='webkit'?webkit:chromium).launch({headless:true,...(process.env.STOCK_CHROMIUM?{executablePath:process.env.STOCK_CHROMIUM,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--single-process']}: {})});const context=await browser.newContext({viewport:{width:440,height:956}});await context.route('https://**/*',r=>r.abort());const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://localhost:8766');await page.waitForFunction(()=>typeof StockUI!=='undefined'&&StockUI.ready);
 const test=async(name,fn)=>{await fn();results.push(name);console.log('PASS',name)};
 await test('Initial application / mobile width / no errors',async()=>{assert.deepEqual(errors,[]);assert.equal(await page.title(),'PCI Stock · 0.2.0');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true)});
 await page.evaluate(()=>{window.fixture={tcg:'pokemon',provider:'tcgdex',referenceId:'base1-1',name:'フシギダネ Á "carta"',set:'Base',number:'001/102',language:'en',variant:'',finish:'',condition:'',location:'A1',cost:'',price:'',currency:'',notes:'=HYPERLINK("https://example.invalid")\nSegunda; línea',referenceImage:''}});
 await test('One action is idempotent under concurrent double press',async()=>{const r=await page.evaluate(async()=>{await Promise.all([Stock.add(fixture,1,'entry-1'),Stock.add(fixture,1,'entry-1')]);return Stock.snapshot()});assert.equal(r.products[0].quantity,1);assert.equal(r.movements.length,1)});
 await test('Two identical copies in distinct actions add two units',async()=>{assert.equal(await page.evaluate(async()=>{await Stock.add(fixture,1,'entry-2');return(await Stock.snapshot()).products[0].quantity}),2)});
 await test('Language, unknown vs confirmed variants and location split SKU',async()=>{const d=await page.evaluate(async()=>{await Stock.add({...fixture,language:'es'},1,'entry-es');await Stock.add({...fixture,variant:'primera edición'},1,'entry-first');await Stock.add({...fixture,finish:'holo'},1,'entry-holo');await Stock.add({...fixture,location:'B'},1,'entry-loc');await Stock.add({...fixture,language:''},1,'entry-unknown');return Stock.snapshot()});assert.equal(d.products.length,6)});
 await test('Undo creates inverse ledger entry',async()=>{const d=await page.evaluate(async()=>{await Stock.undo();return Stock.snapshot()});assert.equal(d.products.find(p=>p.language==='').quantity,0);assert.equal(d.movements.at(-1).type,'undo')});
 await test('Negative exit aborts transaction; no movement persisted',async()=>{const r=await page.evaluate(async()=>{const d=await Stock.snapshot();try{await Stock.move(d.products[0].id,900,'exit','venta','bad');return false}catch{const next=await Stock.snapshot();return JSON.stringify(d)===JSON.stringify(next)}});assert.equal(r,true)});
 await test('Exit, adjustment, stale revision protection',async()=>{assert.equal(await page.evaluate(async()=>{const p=(await Stock.snapshot()).products.find(p=>p.language==='en'&&!p.variant&&!p.finish&&p.location==='A1');await Stock.move(p.id,1,'exit','Venta','sale',p.revision);await Stock.move(p.id,5,'adjustment','Recuento','count');try{await Stock.edit(p.id,fixture,'viejo',p.revision);return false}catch{return(await Stock.snapshot()).products.find(x=>x.id===p.id).quantity===5}}),true)});
 await test('Collision requires consent; merge preserves IDs, quantities and ledger',async()=>{const r=await page.evaluate(async()=>{const d=await Stock.snapshot(),p=d.products.find(p=>p.language==='es'),q=d.products.find(p=>p.language==='en'&&!p.variant&&!p.finish&&p.location==='A1');let collision=false;try{await Stock.edit(p.id,{...p,language:'en'},'corregir idioma',p.revision)}catch(e){collision=!!e.collision}await Stock.edit(p.id,{...p,language:'en'},'fusionar idioma',p.revision,true);const n=await Stock.snapshot();Stock.validate(await Stock.backup());return{collision,source:n.products.find(x=>x.id===p.id),target:n.products.find(x=>x.id===q.id)}});assert.equal(r.collision,true);assert.equal(r.source.quantity,0);assert.equal(r.source.mergedInto,r.target.id);assert.equal(r.target.quantity,6)});
 await test('Real IndexedDB survives reload; own namespace',async()=>{await page.reload();await page.waitForFunction(()=>StockUI.ready);assert.equal(await page.evaluate(async()=> (await Stock.snapshot()).products.length),6);assert.equal(await page.evaluate(()=>Stock.DB),'pci-stock-inventory-v1');assert.equal(await page.evaluate(async()=> (await indexedDB.databases()).some(d=>d.name==='pci-pokemon-reference-v1')),false)});
 await test('JSON validation, tamper rejection, restore and duplicate import guard',async()=>{const r=await page.evaluate(async()=>{const b=await Stock.backup(),p=await Stock.prepareImport(JSON.stringify(b));const bad=structuredClone(b);bad.products[0].quantity++;let invalid=false;try{Stock.validate(bad)}catch{invalid=true}const restored=await Stock.importBackup(p,'replace');const dup=await Stock.importBackup(p,'merge');const overlapping=await Stock.backup();overlapping.products[0].notes+=' changed';let overlap=false;try{await Stock.importBackup(await Stock.prepareImport(JSON.stringify(overlapping)),'merge')}catch{overlap=true}Stock.validate(await Stock.backup());return{invalid,restored,dup,overlap}});assert.equal(r.invalid,true);assert.equal(r.dup.duplicate,true);assert.equal(r.overlap,true)});
 await test('CSV BOM, quotes, newlines, Unicode and formula neutralization',async()=>{const csv=await page.evaluate(async()=>StockExport.csv((await Stock.snapshot()).products));assert.equal(csv.charCodeAt(0),65279);assert(csv.includes('001/102'));assert(csv.includes('フシギダネ Á ""carta""'));assert(csv.includes('"\'=HYPERLINK('));assert(csv.includes('\nSegunda; línea'));fs.writeFileSync('/tmp/pci-stock-test.csv',csv)});
 await test('Real XLSX strings preserve number, IDs and formula-looking text',async()=>{const r=await page.evaluate(async()=>{const d=await Stock.snapshot(),bytes=await StockExport.xlsx(d.products,d.movements),w=new ExcelJS.Workbook();await w.xlsx.load(bytes);const s=w.getWorksheet('Inventario');return{number:s.getCell('G2').value,type:s.getCell('G2').type,notes:s.getCell('S2').value,quantityType:s.getCell('L2').type,log:!!w.getWorksheet('Movimientos'),bytes:Array.from(new Uint8Array(bytes))}});assert.equal(r.number,'001/102');assert.equal(r.type,3);assert.equal(r.quantityType,2);assert.equal(r.log,true);assert.equal(typeof r.notes,'string');fs.writeFileSync('/tmp/pci-stock-test.xlsx',Buffer.from(r.bytes))});
 await test('Storage write failure rolls back product AND movement',async()=>{assert.equal(await page.evaluate(async()=>{const before=await Stock.snapshot(),p=before.products.find(p=>!p.mergedInto&&p.quantity>0),original=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args){if(this.name==='movements')throw new DOMException('Quota simulation','QuotaExceededError');return original.apply(this,args)};let failed=false;try{await Stock.move(p.id,1,'entry','fallo simulado','quota-test')}catch{failed=true}finally{IDBObjectStore.prototype.put=original}return failed&&JSON.stringify(before)===JSON.stringify(await Stock.snapshot())}),true)});
 await test('Disjoint backup import keeps metadata and rejects repetition',async()=>{const r=await page.evaluate(async()=>{const b=await Stock.backup(),base=b.products.find(p=>!p.mergedInto),id=Stock.uuid(),date=new Date().toISOString();const p={...base,id,referenceId:'independent-import',quantity:3,revision:1,createdAt:date,updatedAt:date,mergedInto:null};const backup={...b,backupId:Stock.uuid(),products:[p],movements:[{id:Stock.uuid(),ordinal:1,productId:id,type:'entry',delta:3,before:0,after:3,date,reason:'Inventario externo'}],imports:[],meta:[{...b.meta[0],installationId:Stock.uuid()}]};const prepared=await Stock.prepareImport(JSON.stringify(backup));await Stock.importBackup(prepared);const duplicate=await Stock.importBackup(prepared);const all=await Stock.backup();Stock.validate(all);return{duplicate,quantity:all.products.find(x=>x.id===id).quantity,source:all.imports.at(-1)?.sourceMetadata?.length||all.imports.find(x=>x.id===prepared.hash)?.sourceMetadata?.length}});assert.equal(r.duplicate.duplicate,true);assert.equal(r.quantity,3);assert.equal(r.source,1)});
 await test('Two tabs serialize same entry action in IndexedDB',async()=>{const second=await context.newPage();await second.goto('http://localhost:8766');await second.waitForFunction(()=>StockUI.ready);const add=()=>{return Stock.snapshot().then(d=>Stock.add({...d.products.find(p=>!p.mergedInto),referenceId:'two-tabs'},1,'two-tab-entry'))};await Promise.all([page.evaluate(add),second.evaluate(add)]);assert.equal(await page.evaluate(async()=> (await Stock.snapshot()).products.find(p=>p.referenceId==='two-tabs').quantity),1);await second.close()});
 await test('UI add double click, render cannot add stock, next same card action',async()=>{await page.evaluate(()=>{newInspection();state.identification={card:{name:'UI Test',set:'Base',number:'001/102',referenceId:'ui-1',referenceLanguage:'en'},simulated:false};renderIdentity();renderIdentity()});const before=await page.evaluate(async()=> (await Stock.snapshot()).movements.length);await page.evaluate(()=>{const b=document.querySelector('#stockAdd');b.click();b.click()});await page.waitForFunction(()=>!StockUI.pending);assert.equal(await page.evaluate(async()=> (await Stock.snapshot()).movements.length),before+1);await page.evaluate(()=>{state.identification={card:{name:'UI Test',set:'Base',number:'001/102',referenceId:'ui-1',referenceLanguage:'en'},simulated:false};renderIdentity();document.querySelector('#stockAdd').click()});await page.waitForFunction(()=>!StockUI.pending);assert.equal(await page.evaluate(async()=> (await Stock.snapshot()).products.find(p=>p.referenceId==='ui-1').quantity),2)});
 await test('Inventory screen, filters, edit, history UI',async()=>{await page.click('[data-stock-tab="inventory"]');await page.fill('#stockQuery','UI Test');assert.equal(await page.locator('.stock-item').count(),1);await page.locator('[data-edit-stock]').click();await page.fill('#edit-stock-location','Caja 4');await page.fill('#stockEditReason','Ubicación inicial');await page.click('#stockEditForm button[type="submit"]');await page.waitForFunction(()=>!document.querySelector('#stockDialog').open);assert((await page.locator('.stock-item').innerText()).includes('Caja 4'));await page.locator('[data-history-stock]').click();assert((await page.locator('.stock-log').innerText()).includes('Ubicación inicial'));await page.click('#stockCloseDialog')});
 await test('Front-only recognition flow preserves automatic ES/EN pipeline (mocked providers)',async()=>{const r=await page.evaluate(async()=>{newInspection();window.savedEngine={normalizeForRecognition,recognitionEvidence19,compareCandidates,catalog:PokemonDatabase.catalog,detail:PokemonDatabase.detail,set:PokemonDatabase.set,vs:VisualIndex18.search,js:JapaneseIndex19.search};window.flowCalls=[];normalizeForRecognition=async(side)=>{flowCalls.push(side)};recognitionEvidence19=async()=>({text:'Bulbasaur HP 60',bottom:'001/102 EN',numbers:[{number:'1',total:'102',raw:'001/102'}],name:'Bulbasaur',languageResolution:{language:'en'},manual:false});VisualIndex18.search=async()=>({hits:[],language:'en'});JapaneseIndex19.search=async()=>({hits:[],language:'ja'});PokemonDatabase.catalog=async lang=>{flowCalls.push('catalog:'+lang);return{cards:[{id:'base1-1',localId:'1',name:'Bulbasaur'}],sets:[{id:'base1',name:'Base',cardCount:{official:102}}]}};PokemonDatabase.detail=async()=>({id:'base1-1',localId:'1',name:'Bulbasaur',set:{id:'base1',name:'Base',cardCount:{official:102}}});PokemonDatabase.set=async()=>({id:'base1',name:'Base'});compareCandidates=async()=>({tested:0,failed:0});state.images.front={src:'test',name:'front.png',width:630,height:880};await pairedIdentify();return{back:!!state.images.back,identity:state.identification?.card.referenceId,calls:flowCalls,error:state.recognitionError}});assert.equal(r.back,false);assert.equal(r.identity,'base1-1');assert.equal(r.error,null);assert(r.calls.includes('catalog:es')&&r.calls.includes('catalog:en'))});
 await test('Capture remains single-frame, no OCR gating; upload auto-identifies with no reverse',async()=>{const r=await page.evaluate(async()=>{newInspection();let seen=0;const old=pairedIdentify;pairedIdentify=async()=>seen++;const cv=document.createElement('canvas');cv.width=300;cv.height=420;cv.getContext('2d').fillRect(0,0,300,420);const blob=await new Promise(r=>cv.toBlob(r,'image/png'));await loadFile(new File([blob],'front.png',{type:'image/png'}),'front');const result={seen,front:!!state.images.front,back:!!state.images.back,multi:await Holo19.collect({},{}),views:Holo19.finalize({}).viewCount};pairedIdentify=old;return result});assert.equal(r.seen,1);assert.equal(r.back,false);assert.equal(r.multi,false);assert.equal(r.views,1)});
 await test('Cancellation discards stale recognition before catalog write',async()=>{const r=await page.evaluate(async()=>{newInspection();state.images.front={src:'test',name:'front.png'};let resume;VisualIndex18.search=()=>new Promise(r=>resume=r);const work=pairedIdentify();await new Promise(r=>setTimeout(r,20));newInspection();resume({hits:[]});await work;return !state.identification&&!state.busy});assert.equal(r,true)});
 await page.reload();await page.waitForFunction(()=>StockUI.ready);await page.click('[data-stock-tab="inventory"]');await page.screenshot({path:'/tmp/pci-stock-inventory.png',fullPage:true});await page.click('[data-stock-tab="scan"]');await page.screenshot({path:'/tmp/pci-stock-scan.png',fullPage:true});assert.deepEqual(errors,[]);fs.writeFileSync('/tmp/pci-stock-tests.json',JSON.stringify({browser:process.env.STOCK_BROWSER||'chromium',passed:results,errors},null,2));console.log('TOTAL',results.length,'passed');
 }finally{await browser?.close();server.kill()}
})().catch(e=>{console.error(e);process.exit(1)});
