const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert/strict');
const code=fs.readFileSync(path.resolve(__dirname,'../assets/stock-reliability.js'),'utf8').split('const reliabilityRender=')[0]+'\nglobalThis.rules=StockReliability;';const context={normalizedNumber:v=>String(v??'').toUpperCase().replace(/^([A-Z]*)0+(?=\d)/,'$1')};vm.createContext(context);vm.runInContext(code,context);const R=context.rules;
const card=(id,n,total,lang,score)=>({card:{id,localId:n,name:'Same artwork'},detail:{id,localId:n,set:{id:'set',cardCount:{official:total}}},lang,score,visual:.85,nameMatch:1,reasons:[],audit:{conflicts:[]}});
const e={numbers:[{number:'1',total:'102',raw:'001/102',corrected:false}],footerConfidence:80,languageResolution:{language:'en'}};
const cs=[card('wrong-number','2',102,'en',230),card('wrong-total','1',150,'en',240),card('wrong-language','1',102,'es',260),card('correct','001',102,'en',130)];R.rank(cs,e);assert.equal(cs[0].card.id,'correct');assert.equal(cs[0].stockEvidence.tier,'corroborated');assert(cs.slice(1).every(c=>c.stockEvidence.tier==='conflict'));console.log('PASS printed number, collection total and language override stronger shared artwork scores');
assert.equal(R.printed({...e,footerConfidence:30}),null);assert.equal(R.printed({...e,numberConflict:true}),null);assert.equal(R.printed({...e,numbers:[...e.numbers,{number:'2',total:'102'}]}),null);console.log('PASS weak, conflicting and ambiguous OCR is not treated as independent corroboration');
const visual=[card('visual-only','1',102,'en',170)];R.rank(visual,{numbers:[],languageResolution:{language:null}});assert.equal(visual[0].stockEvidence.tier,'proposal');console.log('PASS artwork without printed evidence remains a proposal');
let calls=0;context.$=()=>({textContent:''});context.RecognitionJobs={check(){}};context.flexibleNumbers=()=>[{number:'1',total:'102',raw:'001/102',corrected:false}];context.retryFooter=async()=>{calls++;return{text:'001/102',confidence:80}};
(async()=>{await R.refine(structuredClone(e),{},1);assert.equal(calls,0);const refined=await R.refine({numbers:[],languageResolution:{language:'en'}},{},1);assert.equal(calls,1);assert(R.printed(refined));const contradicted=await R.refine({numbers:[{number:'2',total:'102',corrected:false}],footerConfidence:30,languageResolution:{language:'en'}},{},1);assert(contradicted.numberConflict);assert.equal(R.printed(contradicted),null);console.log('PASS targeted footer reread only when needed; conflicting reread flagged')})().catch(e=>{console.error(e);process.exit(1)});
